import asyncio
import json

from fastapi import APIRouter, BackgroundTasks, Depends
from fastapi.responses import HTMLResponse, Response
from sqlalchemy.orm import Session

from app.config import Settings, get_settings
from app.database import get_db
from app.errors import raise_api_error
from app.models import Scan, ScanStatus
from app.schemas import Finding, ScanCreate, ScanDetail, ScanProgress, ScanSummary
from app.services.finding_utils import enrich_findings
from app.services.owasp import progress_for_status
from app.services.scan_orchestrator import ScanOrchestrator
from app.services.target_guard import validate_scan_request

router = APIRouter(prefix="/api/scans", tags=["scans"])


def _run_scan_task(scan_id: int, settings: Settings):
    from app.database import SessionLocal

    db = SessionLocal()
    try:
        orchestrator = ScanOrchestrator(settings, db)
        asyncio.run(orchestrator.run(scan_id))
    finally:
        db.close()


@router.post("", response_model=ScanSummary, status_code=201)
def create_scan(
    payload: ScanCreate,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db),
    settings: Settings = Depends(get_settings),
):
    url = validate_scan_request(payload.target_url, payload.authorised)

    scan = Scan(target_url=url, status=ScanStatus.QUEUED, status_message="Queued for scanning")
    db.add(scan)
    db.commit()
    db.refresh(scan)

    background_tasks.add_task(_run_scan_task, scan.id, settings)
    return scan


@router.get("", response_model=list[ScanSummary])
def list_scans(db: Session = Depends(get_db)):
    return db.query(Scan).order_by(Scan.created_at.desc()).limit(50).all()


@router.get("/{scan_id}", response_model=ScanDetail)
def get_scan(scan_id: int, db: Session = Depends(get_db)):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise_api_error(404, "NOT_FOUND", "Scan not found")

    findings = []
    if scan.findings_json:
        findings = enrich_findings([Finding(**f) for f in json.loads(scan.findings_json)])

    return ScanDetail(
        id=scan.id,
        target_url=scan.target_url,
        status=scan.status.value,
        status_message=scan.status_message,
        scanner_used=scan.scanner_used,
        risk_grade=scan.risk_grade,
        finding_count=scan.finding_count,
        critical_count=scan.critical_count,
        high_count=scan.high_count,
        created_at=scan.created_at,
        completed_at=scan.completed_at,
        findings=findings,
        executive_summary=scan.executive_summary,
        ai_report=scan.ai_report,
        error_message=scan.error_message,
    )


@router.get("/{scan_id}/progress", response_model=ScanProgress)
def scan_progress(scan_id: int, db: Session = Depends(get_db)):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise_api_error(404, "NOT_FOUND", "Scan not found")
    return ScanProgress(
        id=scan.id,
        status=scan.status.value,
        status_message=scan.status_message,
        progress_percent=progress_for_status(scan.status.value),
        finding_count=scan.finding_count,
    )


@router.get("/{scan_id}/report/html", response_class=HTMLResponse)
def export_html(scan_id: int, db: Session = Depends(get_db)):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan or not scan.ai_report:
        raise_api_error(404, "NOT_FOUND", "Report not available")

    import markdown

    body = markdown.markdown(scan.ai_report, extensions=["tables", "fenced_code"])
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>ShieldScan Report — {scan.target_url}</title>
<style>
body{{font-family:Georgia,serif;max-width:900px;margin:40px auto;padding:0 20px;line-height:1.6;color:#1a1a2e}}
h1{{color:#0f3460;border-bottom:3px solid #e94560;padding-bottom:10px}}
h2{{color:#16213e;margin-top:30px}}
h3{{color:#533483}}
.meta{{background:#f0f4f8;padding:15px;border-radius:8px;margin-bottom:30px}}
.grade{{font-size:2em;font-weight:bold;color:#e94560}}
footer{{margin-top:40px;color:#888;font-size:0.9em;border-top:1px solid #ddd;padding-top:15px}}
</style></head><body>
<div class="meta">
<p><strong>Target:</strong> {scan.target_url}</p>
<p><strong>Risk Grade:</strong> <span class="grade">{scan.risk_grade or 'N/A'}</span></p>
<p><strong>Findings:</strong> {scan.finding_count} | <strong>Scanner:</strong> {scan.scanner_used}</p>
<p><strong>Generated:</strong> {scan.completed_at or scan.created_at}</p>
</div>
{body}
<footer>Generated by ShieldScan — AI-Assisted Web Vulnerability Assessment Tool</footer>
</body></html>"""
    return HTMLResponse(html)


@router.get("/{scan_id}/report/download")
def download_report(scan_id: int, db: Session = Depends(get_db)):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan or not scan.ai_report:
        raise_api_error(404, "NOT_FOUND", "Report not available")
    content = scan.ai_report.encode("utf-8")
    filename = f"shieldscan-report-{scan_id}.md"
    return Response(
        content=content,
        media_type="text/markdown",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
